### ISSUE TITLE
Randomization Issues

### ISSUE THREAD

**Issue by ItsNotPizza** [iamasink/lilysbot#30]
First off, let's address the randomization issues. Now, ain't it a wonder when a bot can't even handle the most basic form of unpredictability? It's like expecting a lion not to turn you into its chew toy. Not gonna happen, sweetheart. Lily's bot seems to have some sort of fery within its circuits that can't comprehend

**Comment by iamasink** [comment]
Please be more respectful when filling out an Git Hub issue. Closed.
