### ISSUE TITLE
please fix your bot

### ISSUE THREAD

**Issue by No767** [iamasink/lilysbot#8]
an error occurred
Error: write EPROTO C0E75AD4FE7E0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1600:SSL alert number 80

**Comment by iamasink** [comment]
fixed 🤓

**Comment by No767** [comment]
> fixed 🤓 
> some pihole list had api.openai.com blocked for some reason lol

Lol this is why you run your bot on a vps not on a homelab

**Comment by iamasink** [comment]
> > fixed 🤓
> > some pihole list had api.openai.com blocked for some reason lol
> 
> Lol this is why you run your bot on a vps not on a homelab

im poor bitch
